services:
  web-client:
    depends_on:
      - llm-app-server
    image: node:22.14.0-slim
    ports:
      - 5173:5173
    working_dir: /app
    environment:
      VITE_API_BASE_URL: "http://llm-app-server:8000"
    volumes:
      - ./web-client:/app
      - web-client-node-modules:/app/node_modules
    command: /bin/sh -c "npm install && npm run dev"
  
  llm-app-server:
    build:
      context: ./llm-app-server
      target: development
      args:
        PYTHON_VERSION: 3.11.11
    ports:
      - 8000:8000
    environment:
      GOOGLE_CLOUD_PROJECT: emulator
    volumes:
      - ./llm-app-server:/app
      - llm-app-server-venv:/app/.venv
    command:
      ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--log-config", "src/logging.ini", "--reload"]
    tty: true

volumes:
  web-client-node-modules:
  llm-app-server-venv:
